# Automate build for VPI
dist: xenial
services:
  - docker
language: rust
cache: cargo

script:
  - source ~/virtualenv/python3.7/bin/activate
  - python --version
  - pip --version
  - cd firmware_borosVPi
  - python tools.py install
  - make all
  - cd ../vpid
  - cargo install cross
  - ./buildall.sh