# Automate build for VPI
dist: xenial
services:
  - docker
language: rust
cache: cargo

script:
  - cd firmware_borosVPi
  - python tools.py install
  - make all
  - cd ../vpid
  - cargo install cross
  - ./buildall.sh