# Automate build for VPI
dist: xenial

services:
  - docker

jobs:
  include:
    - language: python
      python: 3.7
      before_install:
        - cd firmware_borosVPi
      install: 
        - python tools.py install
      before_script:
        - cd firmware_borosVPi
      script:
        - make all
    

