# Automate build for VPI
dist: xenial

services:
  - docker

jobs:
  include:
    - language: python
      python: 3.7
      install: cd firmware_borosVPi && python tools.py install
      script: cd firmware_borosVPi && make all

      