[package]
name = "vpidctl"
version = "0.1.1"
authors = ["boros"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
vpi = { path = "../vpi" }
clap = "2.33"
ansi_term= "0.12"
serde_json = "1.0"
