#TC = toolchain

UNAME_S := $(shell uname -s)
ifeq ($(UNAME_S),Linux)
        TC :=toolchain/linux
        STAT :=stat -L -c %s
endif

ifeq ($(UNAME_S),Darwin)
        TC :=toolchain/darwin
        STAT :=stat -f %z
endif

UNAME_P := $(shell uname -m)
ifeq ($(UNAME_P),x86_64)
        TC :=$(TC)_x86_64
endif

$(info Starting STM8 Make....   )
$(info Using toolchain [$(TC)] )

# Uncomment to use installed platformio
#TC := $(HOME)/.platformio/packages

# Tools paths
CC =  $(TC)/toolchain-sdcc/bin/sdcc
LD =  $(TC)/toolchain-sdcc/bin/sdld
AS =  $(TC)/toolchain-sdcc/sdasstm8 
OBJCOPY = $(TC)/tool-stm8binutils/bin/stm8-objcopy 
OBJSIZE = $(TC)/tool-stm8binutils/bin/stm8-size
FLASH	= $(TC)/tool-stm8tools/stm8flash
OPENOCD = $(TC)/tool-openocd/bin/openocd

# Configuration items
#MCU= stm8s103f3
MCU := stm8s003f3
F_CPU := 16000000
SERIAL_BAUD := 9600
CFLAGS_EXTRA=  -DUART_STDIO -DVPI_DEBUG 
#-DVPI_CCO